name: mobius_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2
  json_path: ^0.7.4
  path_provider: ^2.1.4
  flutter_pdfview: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
